### PR TITLE
Lambda Default after reboot/closeout

### LINKED ISSUE #21: Can anything be done about this? link almost plays but doesn't?
I've personally constantly dealt with this issue. anything can be done about it on the addon side? the link will half load and alllllmost play. I've gotten this issue for the past few months 

https://www.reddit.com/r/Addons4Kodi/comments/9y57ax/dead_link_handling_in_addons/

### PR DESCRIPTION
**Pull request by 13Clowns**
Add Documentary Section 
Addon.xml - Youtube installs by default
Default.py - add Docuheaven navigator
Service.py - uncomment repo, may help in debugging

### CODE REVIEW

**Comment by SerpentDrago** [comment]
Thank you for Contributing changes/fix's

**Comment by host505** [comment]
@13Clowns so if I understood correctly, your proposed solution to scraper choice resetting (never had this btw) is to disable the ability to choose internal scrapers?

Side note: as you have another pr on the same repo open, your other commits are included in this one as well.
To avoid this, and create 2 separate prs with different commits, you should create different branches in your fork, each one with the proposed corresponding changes.

**Comment by 13Clowns** [comment]
@host505  We haven't had this issue either, although we did notice that when you select default sources the source folder is empty with the exception of trailers.py. This also causes a "NO STREAMS" message. So why have it as an option if there are no scrapers?

If we missed something let me know. 

We will change PR going forward.

**Comment by host505** [comment]
As I understand it, exodus redux was supposed to be a neutral add-on, that only provided trailers by default.
User had to explicitly lambdascrapers (on the first iteration of the plugin lambdascrapers where not even installed by default, dependency was optional.
This plugin was supposed to be something like a template.
That changed at some point, and ls became a mandatory dependency, and also the default scraper selection.

But if you propose to ditch the internal scrapers completely (I don't agree but it's not my call, not my plugin), there are more things to be done than settings mods: sources.py adjustments etc.

**Comment by I-A-C** [comment]
@13clowns, thank you for contribution.

 @host505 observation that exodusredux is supposed to be a sort of template is spot on.  I started this project because I was amazed that after all these years, the general framework/template that lambda put out still works with some minor tweaking.  Everybody wants to reinvent the wheel, I just wanted to keep the wheel rolling and followed through on suggestions that separating the sources module from the addon itself would be a good way to do that.  2 months later, that seems to be bearing out.

I'm drawn to coding side of development and care very little about looks and lists.  On the other hand, I know that others spend quite a bit of time creating new content through the use of custom menus and curated list.  Since I'm not a content creator, I'm hesitant to just grab someone content, unless it's open-source.  

The use of custom art, menus and lists is what differentiates one from another and differentiation should make for a better user experience.  I encourage anyone who wants to try their hand at creating their own addon to use ExodusRedux as a template to start from.  Fork/copy/paste whatever.  The more addons that implement Lambdascrapers the better.

**Comment by jewbmx** [comment]
Who tested the LS on a jen template? lol

**Pull request closed without merging**
